### ISSUE TITLE
What was the prompt used to generate the code?

### ISSUE THREAD

**Issue by Beliavsky** [YB-LIM/ChatGPT_GAPCON#1]
What was the prompt given to ChatGPT to generate the code GAPCON.f?

**Comment by YB-LIM** [comment]
Please refer to the following Linkedin post:
https://www.linkedin.com/posts/lyb0684_chatgpt-abaqus-subroutine-activity-7044931314159927296-NZI-?utm_source=share&utm_medium=member_android

**Comment by Beliavsky** [comment]
Thanks -- I suggest adding a link to this in the Readme.

**Comment by YB-LIM** [comment]
Thanks for the suggestion. It is now added in the Readme
